spring.application.name=curso-kafka-spring
#logging.level.org.springframework.kafka=WARN
#logging.level.org.apache.kafka=WARN
logging.level.org.apache.kafka.clients.consumer.ConsumerConfig=INFO
logging.level.org.apache.kafka.clients.producer.ProducerConfig=INFO